title =  "蘭陵N散記"
languageCode = "zh-CN"
baseurl = "http://lanlingzi.cn"
copyright =  "蘭陵N散記-www.lanlingzi.cn Copyright © 2015. All rights reserved."
theme =  "hueman"
MetaDataFormat =  "yaml"
canonifyurls =  true
builddrafts =  false
PaginatePath =  "p"
Paginate = 11
RSSUri =  "feed.xml"
disablePathToLower =  false
hasCJKLanguage =  true
preserveTaxonomyNames = false
uglyurls = false

[Taxonomies]
  category = "categories"
  tag = "tags"

[params]
  Tagline =  "一指流沙，程序年华"
  Description =  "韶华易逝，往昔不再"
  Keywords =  "独立博客,程序员,架构师,思考,读书笔记,技术分享"
  AuthorName =  "兰陵子"
  Bio = "Programmer - Architect"
  Location = "Shenzhen,China"
  GitHubUser =  "xtfly"
  GitHubRepository =  "xblog"
  SidebarRecentLimit =  8
  DateForm =  "2006年01月02日"
  SyntaxHighlightTheme =  "github.min.css"
  Categories = ["技术" ,"笔记", "感想", "杂记"]

[[menu.main]]
  Name = "归档"
  Pre = "<i class='fa fa-heart'></i>"
  Weight = -110
  Identifier = "post"
  URL = "/post/"
[[menu.main]]
  Name = "关于"
  Pre = "<i class='fa fa-road'></i>"
  Identifier = "about"
  Weight = -100
  URL = "/about/"

images = ["480x", "768x", "960x", "1024x", "1920x", "720x340", "520x245"]
