title =  "蘭陵N散記"
languageCode = "zh-CN"
baseurl = "http://lanlingzi.cn/"
theme =  "pacman"
MetaDataFormat =  "yaml"
canonifyurls =  true
builddrafts =  false
PaginatePath =  "p"
Paginate = 15
RSSUri =  "feed.xml"
disablePathToLower =  false
hasCJKLanguage =  true
preserveTaxonomyNames = false
uglyurls = false
pygmentsStyle = "default"
pygmentsUseClasses = true

[Params]
  AuthorHomepage = "http://lanlingzi.cn/"
  BottomIntroduce = "一指流沙，程序年华"
  Description = "韶华易逝，往昔不再"
  Subtitle = "一指流沙，程序年华"
  GitHub = "xtfly"
  Imglogo = "img/logo.png"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true

[Author]
  Name = "兰陵子"

[Params.DuoShuo]
  ShortName = "lanlingzi"

[Params.Strings]
  Search = "搜索"
  PageNotFound = "你访问的页面不存在"
  ShowSideBar = "显示侧边栏"
  HideSideBar = "隐藏侧边栏"
  Categories = "分类"
  Archive = "归档"
  Tags = "标签"
  TagCloud = "标签云"
  Rss = "RSS 订阅"
  TableOfContents = "文章目录"

[[Menu.Main]]
  Name = "首页"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "归档"
  Weight = 2
  URL = "/post/"
[[Menu.Main]]
  Name = "关于"
  Weight = 3
  URL = "/about/"
[[Menu.Main]]
  Name = "订阅"
  Weight = 4
  URL = "/feed.xml"
